### ISSUE TITLE
Could we make these features available on Eclipse update site?

### ISSUE THREAD

**Issue by pjpaulin** [ECF/JaxRSProviders#19]
These features are great and you should know they're being used extensively in some very mission-critical applications. So thank you for doing this work.

I was wondering if there are any plans to make these features available in the regular ECF update site on eclipse.org. For some reason it's not possible to point an Eclipse target definition at the URL on GitHub (build) directory, even though it's a valid p2 repository. 

Also, the clients I work with are more comfortable if they're mirroring an Eclipse p2 repo, they look at me funny if I hand them a zip archive from GitHub...

Thanks,

--- Patrick

**Comment by scottslewis** [comment]
> 
> 
> These features are great and you should know they're being used extensively in some very >mission-critical applications. So thank you for doing this work.

Welcome.  I'm happy to hear that folks are using it.    Any public comments (like this) about usage, issues, feature enhancements, are very much appreciated.

> 
> I was wondering if there are any plans to make these features available in the regular ECF update >site on eclipse.org. 

Do you mean a p2 site?   I assume so based upon what you say below, but want to make sure as we already support a karaf feature at eclipse.org that points at the karaf-features.xml in the build directory.

>For some reason it's not possible to point an Eclipse target definition at the URL on GitHub (build) >directory, even though it's a valid p2 repository.

I haven't tried this myself, so you might be right...but are you using the 'raw' url in the target platform?  e.g. with url of:

https://raw.githubusercontent.com/ECF/JaxRSProviders/master/build

i.e. 
> 
> Also, the clients I work with are more comfortable if they're mirroring an Eclipse p2 repo, they look at me funny if I hand them a zip archive from GitHub...

I understand.  Short answer:   yes this distribution provider in particular could be made available via the eclipse.org ECF p2 repo.  The two barriers to completing this are:  1) releng work (i.e. adding the build of this to the eclipse.org/ecf builder);  2) The eclipse ip mgmt process (as I might need to contribute it to the eclipse.org ECF project.   I have to look into this though as eclipse.org now has content from github repos for other projects, so this may not be a 'big deal' in terms of IP mgmt now. 3) my time to do 1 and 2 (this isn't my full-time gig right now).

Let me know though if you really would like this to happen and I can start the work on releng.  If you or your employer are able to contribute at all to any of 1,2,3 that it would be most appreciated.

Thanks Patrick.

**Comment by pjpaulin** [comment]
Yes, I was looking for an "official" version of the providers as a p2 repository. But the raw URL works great right now (thanks for the tip).

I'm currently without a contract (thanks COVID-19...), focusing on training and research. But I'm going to be promoting these particular features as part of a push to see Eclipse UIs (RCP, RAP, Theia) as well positioned to take advantage of microservice architectures. If I find clients interested in this approach perhaps we could revisit migrating to eclipse.org then.

I do think it would be good to clean up the metadata. I'll close this issue and open another for that.
