### ISSUE TITLE
Clean up metadata for features

### ISSUE THREAD

**Issue by pjpaulin** [ECF/JaxRSProviders#20]
Requesting that the feature names be standardized. Here's what we have now:

ECF CXF Client Distribution Provider Feature
ECF CXF JaxRC Distribution Provier
ECF Remote Services Jersey Server Provider
Jersey Remote Service Client Provider Feature

After looking at the features in the main Eclipse ECF repo, I would suggest something like this:

ECF Remote Services JAX-RS CXF Client Provider
ECF Remote Services JAX-RS CXF Server Provider
ECF Remote Services JAX-RS Jersey Client Provider
ECF Remote Services JAX-RS Jersey Server Provider

**Comment by scottslewis** [comment]
Fixed and released as version 1.13.2.  See [releases](https://github.com/ECF/JaxRSProviders/releases)

**Comment by scottslewis** [comment]
Closing.
