### ISSUE TITLE
Adding needed plug-ins to features

### ISSUE THREAD

**Issue by modular-mind** [ECF/JaxRSProviders#21]
I just created an example project attempting to show best-practices for using these providers. 

https://github.com/modular-mind/spacex-client

I've also written a blog post about this:

https://www.modumind.com/2020/05/19/eclipse-rcp-and-rest-an-introduction/

I'm focused mostly on the Jersey JAX-RS client right now, though these issues may relate to the CXF provider or the server providers as well.

My goal is to have everything cleanly provisioned in a target definition and in an Eclipse RCP product configuration. Ideally that would mean that I could include a small set of features that contain all required plug-ins. Currently my product configuration features are:

--- RCP features ---
org.eclipse.emf.ecore
org.eclipse.emf.common
org.eclipse.e4.rcp

--- ECF features ---
org.eclipse.ecf.core.feature
org.eclipse.ecf.discovery.feature
org.eclipse.ecf.osgi.services.feature
org.eclipse.ecf.remoteservice.feature
org.eclipse.ecf.provider.jersey.client.feature

This looks good, except there are 3 plug-ins I have to include in my custom feature:

org.eclipse.equinox.concurrent.future
javax.servlet
javax.activation

Each of these plug-ins has a different story, and I could break them out into three separate issues if you like. But if these plugins could be added to the Jersey JAX-RS Client Provider feature, then it could be easily dropped into a target or product config and used as is.

**Comment by scottslewis** [comment]
Hi Patrick,
> 
> I just created an example project attempting to show best-practices for using these providers.
> 
> https://github.com/modular-mind/spacex-client
> 
> I've also written a blog post about this:
> 
> https://www.modumind.com/2020/05/19/eclipse-rcp-and-rest-an-introduction/

Great!  Thanks much.  I will take some time to review as soon as I can.

> 
> I'm focused mostly on the Jersey JAX-RS client right now, though these issues may relate to the CXF provider or the server providers as well.
> 
> My goal is to have everything cleanly provisioned in a target definition and in an Eclipse RCP product configuration. Ideally that would mean that I could include a small set of features that contain all required plug-ins. Currently my product configuration features are:
> 
> --- RCP features ---
> org.eclipse.emf.ecore
> org.eclipse.emf.common
> org.eclipse.e4.rcp
> 
> --- ECF features ---
> org.eclipse.ecf.core.feature
> org.eclipse.ecf.discovery.feature
> org.eclipse.ecf.osgi.services.feature
> org.eclipse.ecf.remoteservice.feature
> org.eclipse.ecf.provider.jersey.client.feature
> 
> This looks good, except there are 3 plug-ins I have to include in my custom feature:
> 
> org.eclipse.equinox.concurrent.future
> javax.servlet
> javax.activation

In new release 1.13.3 just created I've added these bundles to the Jersey Client feature (along with Jersey Server feature).   FYI:  the javax.activation bundle is named com.sun.activation.javax.activation.

> 
> Each of these plug-ins has a different story, and I could break them out into three separate issues if you like. But if these plugins could be added to the Jersey JAX-RS Client Provider feature, then it could be easily dropped into a target or product config and used as is.

Please give this a try with 1.13.3 and see how it works.  If not working as desired please feel free to reopen.
