### ISSUE TITLE
Remove example plugins from features

### ISSUE THREAD

**Issue by modular-mind** [ECF/JaxRSProviders#22]
While it's not causing a problem, I think it would be cleaner to remove the example plug-ins from the features. It would help developers to see these features as production quality.

**Comment by scottslewis** [comment]
I've removed the student example bundles from the Jersey (and CXF) server and client features and created a new feature:  org.eclipse.ecf.provider.jaxrs.examples.student.feature.   If this does not satisfy please feel free to reopen.
